"""Dependency-inversion ports shared by analysis and infrastructure."""

from typing import Any, Protocol

from .domain.knowledge import CallTarget, EntryPointDef, FunctionDef


class SourceProvider(Protocol):
    def read_text(self, path: str) -> str | None: ...

    def snippet(self, path: str, start: int, end: int) -> str | None: ...


class CodeGraphRepository(Protocol):
    def functions(self) -> list[FunctionDef]: ...

    def callers(self, node_id: str) -> list[CallTarget]: ...

    def callees(self, node_id: str) -> list[CallTarget]: ...

    def inbound_endpoints(self) -> list[EntryPointDef]: ...

    def route_nodes(self) -> list[dict[str, Any]]: ...

    def decorated_handlers(self) -> list[dict[str, Any]]: ...

    def module_import_edges(self) -> list[dict[str, Any]]: ...

    def cross_file_call_edges(self) -> list[dict[str, Any]]: ...

    def call_edges(self) -> list[dict[str, Any]]: ...

    def layer_call_edges(self) -> list[dict[str, Any]]: ...

    def file_records(self) -> list[dict[str, Any]]: ...

    def config_candidate_nodes(self) -> list[dict[str, Any]]: ...

    def import_nodes(self) -> list[dict[str, Any]]: ...

    def decorator_nodes(self) -> list[dict[str, Any]]: ...

    def authorization_handlers(self) -> list[dict[str, Any]]: ...

    def authorization_middleware(self) -> list[dict[str, Any]]: ...

    def enum_nodes(self) -> list[dict[str, Any]]: ...

    def enum_members(self, enum_id: str) -> list[dict[str, Any]]: ...

    def functions_named_like(self, name: str) -> list[dict[str, Any]]: ...

    def database_call_candidates(self) -> list[dict[str, Any]]: ...

    def primary_language(self) -> str: ...

    def has_node_name(self, pattern: str) -> bool: ...

    def http_client_calls(self, pattern: str) -> list[dict[str, Any]]: ...

    def function_location(self, qualified_name: str) -> list[dict[str, Any]]: ...

    def url_candidate_nodes(
        self, file_path: str, start_line: int, end_line: int
    ) -> list[dict[str, Any]]: ...

    def mq_producer_calls(self, pattern: str) -> list[dict[str, Any]]: ...

    def mq_consumers(self, pattern: str) -> list[dict[str, Any]]: ...

    def topic_candidate_nodes(self, file_path: str) -> list[dict[str, Any]]: ...

    def rpc_calls(self, pattern: str) -> list[dict[str, Any]]: ...

    def business_entity_nodes(self) -> list[dict[str, Any]]: ...
